### PR TITLE
Port to dune

### PR DESCRIPTION
**Pull request by maiste**
The OCaml ecosystem more relies on `dune` to build a package and `opam monorepo` requires the package to work with  `dune`. This PR ports `ocaml-inotiify` to this build system to be more compatible with the current ecosystem.

### CODE REVIEW

**Comment by whitequark** [comment]
Thank you!

**Comment by maiste** [comment]
You're welcome :smile: 
Do you think it is possible to do a release with this version of the build system?

**Comment by whitequark** [comment]
Probably not. I haven't used OCaml in a few years, and now that I try to use opam, neither `--solver=mccs` nor `--solver=aspcud` let me install a new switch, and I don't feel like figuring out why.

**Comment by maiste** [comment]
Thanks so much! :)

**Comment by whitequark** [comment]
I'm getting this error running `make`:
```
dune build .
File "lib_test/dune", line 8, characters 20-31:
8 |   (libraries ounit2 inotify.lwt fileutils )
                        ^^^^^^^^^^^
Error: Library "inotify.lwt" in _build/default/lib is hidden (optional with
unavailable dependencies).
Hint: try:
  dune external-lib-deps --missing .
```

**Comment by maiste** [comment]
I'm taking a look at it!

**Pull request merged**
